@startuml

left to right direction
skinparam packageStyle rectangle

actor "Пользователь" as user
actor "Администратор" as admin

rectangle "Система конференц-связи и чатов" {
  usecase "Регистрация" as UC1
  usecase "Вход в систему" as UC2
  usecase "Управление личным кабинетом" as UC3
  usecase "Присоединение к видеоконференции" as UC4
  usecase "Отправка сообщений в чат" as UC5
  usecase "Создание чата" as UC6
  usecase "Демонстрация экрана" as UC7
  usecase "Просмотр истории сообщений" as UC8
  usecase "Блокировка пользователя" as UC9
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6
user --> UC7
user --> UC8

admin --> UC9

UC2 ..> UC3 : <<include>>
UC4 ..> UC7 : <<include>>
UC5 ..> UC8 : <<include>>

@enduml
